### ISSUE TITLE
Get involved with RSECon at the start of the process

### ISSUE THREAD

**Issue by twinkarma** [socrse/edia#16]
- [x] Keep an eye out of when the committee is formed
- [x] Invite new EDIA chair to our meetings
Suggestions from disability unconferencing
- https://gist.github.com/sjmf/72ad0553026d3f9a1b5607bb56c0a154

**Comment by sjmf** [comment]
Notes 4/12/23 - @martintoreilly mentions that the only role yet to be filled is the EDIA chair. A couple of people have been approached – they volunteered for other things – didn't want to impose burdens on people who are already doing the lifting on that in the community. Dave Horsfall and Katie Finch want to focus on inclusion and accessibility this time around, and want to make the remote conference experience more accessible.

**Comment by stefpiatek** [comment]
Done!
