### ISSUE TITLE
Restructure website navigation for easier community involvement?

### ISSUE THREAD

**Issue by sjmf** [socrse/edia#17]
We are proposing to add a set of pages on EDIA to the RSE Society website to collect links to resources and showcase the work of the working group. Would be useful to make it easier to find. Proposal in next comment

* Working Group
    - What we do
    - RSE Landscape and EDI strategy
    - How to get involved
    - Terms of reference
* Resources
    - Link to issue #4
* Events and initiatives funding
    - What's available
    - How to apply
    - Things we've funded in the past
* Cross-link to policies
* RSE Stories (https://society-rse.org/careers/rse-journeys/)
    - Link to issue #12

**Comment by stefpiatek** [comment]
I've copied out the current headers and then added in a suggestion for a slight change in structure. Not too strongly held belief that this is the best way, but does make it easier to see how to get involved in the society. Could instead have a working groups and special interest groups section

Also wondering if the resources should just be the link database on its own?

```diff
* About
  * History
  * Governance
  * Policies
  * Accessibility statement
  * Contact
* Community
-  * Get involved (or possibly we keep in and it redirects to get-involved/join-us?)
  * RSE Leaders Meetings
  * RSE Groups
  * RSE Fellows
  * Regional Groups
  * International RSE
  * RSE Catalyst Awards
* Events
  * RSE Conference 2024
  * Browse Events
  * Events and Initiatives Funding
* Careers
  * Vacancies
  * RSE Journeys
* News
* Resources
-  * Link Database
-  * COVID-19
- * Join Us
+ * Get involved
+  * Join us
+  * Membership benefits
+  * EDIA and role diversity
+  * Mentoring
+  * Communications and publicity
+  * Special interest groups
* Members Log in
```

**Comment by twinkarma** [comment]
Bring this to trustee meeting as a discussion point.

**Comment by stefpiatek** [comment]
Discussed in [2024-01-24 January Trustee Meeting](https://docs.google.com/document/d/1i_lN7YDLBEUUZVosVszYAXWqgnOVox6JaFi-p0ZG-is/edit?usp=sharing). Some changes and supportive of changing. Will chat with @twinkarma about rolling this out

**Comment by stefpiatek** [comment]
- [x] also remove this page <https://society-rse.org/society-of-rse-mentoring-scheme-sign-up/> (and change link in <https://society-rse.org/join-us/> under mentoring sign up). Keep <https://society-rse.org/community/get-involved/mentoring-scheme/> as mentoring scheme

**Comment by twinkarma** [comment]
- [x] Create a new "Membership Benefits" page with benefits copied from "Join us"
- [x] EDIA & Role diversity to be put into a single page (Stef)
- [x] Special interest groups page - Cut and paste form get involved page
  - [x] created a link from "get involved" page

**Comment by twinkarma** [comment]
There's two "Get involved" pages, the contents are almost identical:
- https://society-rse.org/community/get-involved/ - Created by Matt, has the latest updates
- https://society-rse.org/community/get-involved-new/ - Created by Jamie Quinn

@milliams Looks like it should be safe to delete the get-involved-new page?

**Comment by milliams** [comment]
> @milliams Looks like it should be safe to delete the get-involved-new page?

Yes, I think so.

**Comment by twinkarma** [comment]
I've created the "Membership benefits" page (https://society-rse.org/wp-admin/post.php?post=9537&action=edit, https://society-rse.org/community/get-involved/membership-benefits/) but it seems a bit redundant as we really should put all the information in the "Join us" page anyway. What do you think @stefpiatek ?

**Comment by twinkarma** [comment]
The COVID-19 page (https://society-rse.org/rse-contributions-to-covid-19-research/) has been removed from Resources, should it be linked from another location on the site?

**Comment by mdsimpson42** [comment]
Hi. Great work on this, it's a definite improvement! 

I've added "Volunteer at RSECon" to the "Get Involved" menu. I already discussed this with Twin & Stef, but it's part of a refactor of how information is presented to potential volunteers, committee members, programme chairs etc. on the website, and this seems like the logical place to put it.

**Comment by stefpiatek** [comment]
> I've created the "Membership benefits" page (https://society-rse.org/wp-admin/post.php?post=9537&action=edit, https://society-rse.org/community/get-involved/membership-benefits/) but it seems a bit redundant as we really should put all the information in the "Join us" page anyway. What do you think @stefpiatek ?

Yeah maybe you're right, I can imagine someone wanting to know why should I join before going to join us. Maybe rename `Join Us` to `Join Us & Benefits`?
