### ISSUE TITLE
[2024] Review elections communications

### ISSUE THREAD

**Issue by twinkarma** [socrse/edia#22]
Ongoing tasks to review elections WG outgoing communications:

- [x] Blog post announcing nominations: https://society-rse.org/?p=9655&preview=1&_ppp=39382f72dc 
- [x] Nomination form
  - View only link: https://forms.gle/zBczshzce67EUGju9
  - Should EDIA information be collected?

Place comments here:
https://docs.google.com/document/d/1kqnC_8MjJGpYtVv8StPwFNI5WVGn55BLm8CiEomIDhM/edit

**Comment by stefpiatek** [comment]
thanks to @louisepb for going through the google doc 👏
