### ISSUE TITLE
Curated list of resources to support EDIA initiatives

### ISSUE THREAD

**Issue by martintoreilly** [socrse/edia#4]
Resources for additional support and guidance

- [x] Add to existing [resources](https://society-rse.org/submit-a-resource-to-the-resource-database/)
   - [creating accessible content](https://www.ucl.ac.uk/isd/services/digital-accessibility-services/creating-accessible-content)
   - [anti-racism toolkit](https://reflect.ucl.ac.uk/ar-lt-tool/)
   - [Ally skills training](https://frameshiftconsulting.com/ally-skills-workshop/)
- [x] cross link from EDIA working group to EDIA resources
- [x] clear instructions on where to send suggestions - edia@society-rse.org  (add the subject default to the mailto url)
- [x] Promote current resources and ask for others when we launch our public EDIA and RD group

**Comment by stefpiatek** [comment]
- [x] Need a home on the RSEsoc website? 
- [x] There should be a decent list in the minutes @quirksahern will drop them in a comment

**Comment by stefpiatek** [comment]
resources

- [creating accessible content](https://www.ucl.ac.uk/isd/services/digital-accessibility-services/creating-accessible-content)
- [anti-racism toolkit](https://reflect.ucl.ac.uk/ar-lt-tool/)
- [Ally skills training](https://frameshiftconsulting.com/ally-skills-workshop/)

**Comment by sjmf** [comment]
Notes 4/12/23 – 
Can we ask for a devolved space on [https://society-rse.org/](https://society-rse.org/) that we can manage resources on? 

Discussed where this should go: preference would be for a front-and-centre EDIA page that we can create pages under.

**Comment by twinkarma** [comment]
Twin: All of these resources would be good to be listed on the dedicated EDIA page which still needs to be designed.

**Comment by twinkarma** [comment]
I've changed Diversity & Inclusivity category to EDIA on our resources page https://society-rse.org/resources/ and added the links.

**Comment by twinkarma** [comment]
Updated the EDIA group page with direct link to our resource library and a link for sending link suggestions.

**Comment by stefpiatek** [comment]
- [x] we should Signpost https://www.bcs.org/membership-and-registrations/member-communities/bcswomen-specialist-group/career-centre/women-in-tech-a-practical-guide-to-increasing-gender-diversity-and-inclusion/
